"""init tables

Revision ID: c9d88c4c92c1
Revises: 
Create Date: 2026-08-15 18:01:57.707299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c9d88c4c92c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('wallet_address', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_wallet_address'), 'agents', ['wallet_address'], unique=True)
    op.create_table('providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('pay_to_address', sa.String(length=80), nullable=False),
    sa.Column('successful_transactions', sa.Integer(), nullable=False),
    sa.Column('failed_transactions', sa.Integer(), nullable=False),
    sa.Column('average_latency_ms', sa.Integer(), nullable=False),
    sa.Column('refund_count', sa.Integer(), nullable=False),
    sa.Column('dispute_count', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spending_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('max_transaction_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('daily_limit', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('min_provider_reputation', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'POLICY_BLOCKED', 'PAYMENT_REQUIRED', 'PAYMENT_SUBMITTED', 'PAYMENT_VERIFIED', 'SERVICE_COMPLETED', 'FAILED', 'REFUNDED', name='transaction_status'), nullable=False),
    sa.Column('payment_reference', sa.String(length=200), nullable=True),
    sa.Column('x402_payment_identifier', sa.String(length=200), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_idempotency_key_unique', 'transactions', ['idempotency_key'], unique=True)
    op.create_table('allowed_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['spending_policies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escrows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('HELD', 'RELEASED', 'REFUNDED', name='escrow_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('escrows')
    op.drop_table('allowed_providers')
    op.drop_index('ix_transactions_idempotency_key_unique', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('spending_policies')
    op.drop_table('providers')
    op.drop_index(op.f('ix_agents_wallet_address'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
